# Generated by Django 5.0.2 on 2024-09-28 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_person_birth_date_alter_person_shirt_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
