# Generated by Django 5.0.2 on 2024-09-28 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_membership_date_joined'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False, 'ordering': ['name']},
        ),
    ]
